name: Dockerize the app

on: [push]
  
jobs:
  Dockerize:
    runs-on: ubuntu-latest
    name: Build image and run the container
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run docker compose
        run: |
          docker compose -f compose.yaml up -d --build
          
      - name: curl to localhost
        run: |
          until docker ps | grep library-website-server-1 && docker ps | grep sql_server_container; do
          echo "Waiting for containers to be up..."
          sleep 1
          done

          echo "Containers are up!"
          curl http://localhost:40000
