name: Dockerize and Test with Kubernetes

on: [push]

jobs:
  Build_Test_Deploy:
    runs-on: ubuntu-latest
    name: Build, Test, and Deploy using Docker & Kubernetes
    env:
      MSSQL_SA_PASSWORD: ${{ secrets.MSSQL_PASSWORD }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Set up Minikube
      - name: Start Minikube
        id: minikube
        uses: medyagh/setup-minikube@latest

      - name: To Load images into Minikube #minikube image load could also be used but it's slow
        run: |
          eval $(minikube docker-env)

      # Build and test with Docker Compose
      - name: Build and run with Docker Compose
        run: |
          docker compose -f compose.yaml up -d --build

      - name: Wait for local Docker app
        run: |
          echo "Waiting for server to be ready on localhost:40000..."
          timeout 30s bash -c ' \
            until curl -sS -f http://localhost:40000; do \
              echo "Server not up yet. Retrying in 2 seconds..."; \
              sleep 2; \
            done'
          echo "Server is up and responding!"

      # Tag images locally (for Kubernetes to use later)
      - name: Tag local images
        run: |
          docker tag library-website-db alperenakkoz/library-website-db:latest
          docker tag library-website-server alperenakkoz/library-website-server:latest
          docker images

      # Deploy to Kubernetes
      - name: Create Kubernetes secret
        run: |
          kubectl create secret generic mssql-secret \
            --from-literal=MSSQL_SA_PASSWORD="${{ secrets.MSSQL_PASSWORD }}"

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/

      - name: Wait for deployments
        run: |
          echo "Waiting for SQL Server deployment..."
          kubectl wait --for=condition=available --timeout=300s deployment/mssql-deployment
          
          echo "Waiting for App deployment..."
          kubectl wait --for=condition=available --timeout=300s deployment/library-app-deployment

      #port-forward creates some output than can hinder other commands > /dev/null 2>&1
      - name: Test Kubernetes deployment
        run: |
          kubectl port-forward service/library-app-service 8080:80 &
          echo "Testing Kubernetes deployment..."
          timeout 30s bash -c ' \
            until curl -sS -f http://localhost:8080; do \
              echo "K8s app not ready yet. Retrying in 2 seconds..."; \
              sleep 2; \
            done'
          echo "Kubernetes test successful!"

      # Push images to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: alperenakkoz
          password: ${{ secrets.DOCKER_LOGIN_PASSWORD }}

      - name: Push images to Docker Hub
        run: |
          docker push alperenakkoz/library-website-db:latest
          docker push alperenakkoz/library-website-server:latest
